Update README file
DeepBlueCLtd/RA-Soul pull request #21
Opened 2024-06-13 13:23 UTC by AbegaM

### Modifications 
1. Updated the name of the package from `ra-soul-provider` to `ra-soul` 
2. Added a note on how to use the `extension` feature of soul with `RA` app

2024-06-13 14:41 UTC, IanMayo requested changes

2024-06-13 14:41 UTC, IanMayo commented on README.md
> +
@AbegaM - didn't we have to create a custom route to serve the static content?

![image](https://github.com/DeepBlueCLtd/RA-Soul/assets/1108513/00552807-1f41-4913-9626-86e7013dbcbf)

2024-06-13 14:41 UTC, IanMayo commented on README.md
> +
(I did provide that feedback earlier this afternoon @AbegaM - but I clicked `review` instead of `submit comment`

2024-06-14 07:08 UTC, AbegaM commented on README.md
> +
Hello @IanMayo, This is the `RA-Provider`. Shouldn't we point the extension example to the `Soul` repository, considering that the extension feature is related to `Soul`?


![Screen Shot 2024-06-14 at 10 07 10 AM](https://github.com/DeepBlueCLtd/RA-Soul/assets/70259638/d0a082e0-264c-4a40-9d80-a45214759db1)
 and this is only a Data provider

2024-06-14 09:34 UTC, IanMayo commented on README.md
> +
Ooh, that's a difficult one. Extensions are intended for consumers of Soul to use, and RA-Soul is a consumer.  But, it's such a valuable extension that yes - I think it is worth documenting it in Soul, with some more explanation.

2024-06-14 10:04 UTC, IanMayo commented on README.md
> +
Thumbs-up from Vahid :-D

2024-06-14 11:06 UTC, AbegaM commented on README.md
> +
Ok Thanks, i will push a PR to `Soul` and will also update the `README` file in this repo

2024-06-18 11:19 UTC, IanMayo approved these changes

2024-06-18 11:19 UTC, merged